from __future__ import annotations

from dataclasses import dataclass
from io import BytesIO
from typing import Iterable

import cv2
import numpy as np
from PIL import Image, ImageOps

PEN_UP_GCODE = "G0 Z5"  # TODO: Verify best Scribit pen-up command on hardware.
PEN_DOWN_GCODE = "G1 Z0"  # TODO: Verify best Scribit pen-down command on hardware.
DEFAULT_FEED_MM_MIN = 1800
MAX_GCODE_WARNING_BYTES = 5 * 1024 * 1024
SUPPORTED_FORMATS = {"png", "jpg", "jpeg", "webp"}


@dataclass
class ConversionResult:
    gcode: str
    preview_svg: str
    path_count: int
    gcode_size_bytes: int
    warning: str | None = None


def _svg_polyline(points: Iterable[tuple[float, float]]) -> str:
    pts = " ".join(f"{x:.2f},{y:.2f}" for x, y in points)
    return f'<polyline points="{pts}" fill="none" stroke="#111" stroke-width="0.4" />'


def convert_image_to_gcode(
    image_bytes: bytes,
    filename: str,
    width_mm: float = 180.0,
    height_mm: float = 180.0,
    simplify_epsilon_px: float = 1.5,
) -> ConversionResult:
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    if ext not in SUPPORTED_FORMATS:
        raise ValueError("Supported image formats are png, jpg, jpeg, and webp.")

    image = Image.open(BytesIO(image_bytes))
    image = ImageOps.exif_transpose(image).convert("L")
    image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
    gray = np.array(image)

    edges = cv2.Canny(gray, threshold1=70, threshold2=160)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

    img_h, img_w = gray.shape[:2]
    scale = min(width_mm / img_w, height_mm / img_h)
    draw_w = img_w * scale
    draw_h = img_h * scale
    x_offset = (width_mm - draw_w) / 2.0
    y_offset = (height_mm - draw_h) / 2.0

    lines: list[str] = [
        "; Generated by Scribit Desktop image_to_gcode.py",
        "G21 ; millimeters",
        "G90 ; absolute coordinates",
        PEN_UP_GCODE,
        f"F{DEFAULT_FEED_MM_MIN}",
    ]
    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width_mm:.2f} {height_mm:.2f}">',
        '<rect width="100%" height="100%" fill="white"/>',
    ]

    path_count = 0
    for contour in contours:
        if len(contour) < 8:
            continue
        approx = cv2.approxPolyDP(contour, simplify_epsilon_px, closed=False)
        pts: list[tuple[float, float]] = []
        for point in approx[:, 0, :]:
            x_px, y_px = float(point[0]), float(point[1])
            pts.append((x_offset + x_px * scale, y_offset + y_px * scale))
        if len(pts) < 2:
            continue
        path_count += 1
        start_x, start_y = pts[0]
        lines.extend([PEN_UP_GCODE, f"G0 X{start_x:.2f} Y{start_y:.2f}", PEN_DOWN_GCODE])
        for x, y in pts[1:]:
            lines.append(f"G1 X{x:.2f} Y{y:.2f}")
        svg_parts.append(_svg_polyline(pts))

    lines.extend([PEN_UP_GCODE, "M2 ; end"])
    svg_parts.append("</svg>")
    gcode = "\n".join(lines) + "\n"
    size = len(gcode.encode("utf-8"))
    warning = "G-code is over 5 MB; Scribit may run into storage/download issues." if size > MAX_GCODE_WARNING_BYTES else None
    return ConversionResult(gcode, "\n".join(svg_parts), path_count, size, warning)
